language: python
python:
  - "3.8"
  - "3.8-dev" 
  #- "nightly"  # nightly build
before_install:
  - python3 --version
  - pip3 install -U pip
env: 
    - BASE_URL=http://covid-chatterbot.herokuapp.com/
install:
  - pip3 install -r requirements.txt
script:
  - pytest
